services:
  web:
    image: 12tkj-harbas-web:latest
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        BUILDKIT_INLINE_CACHE: "1"
    container_name: 12tkj-harbas-web
    ports:
      - "8213:8213"
    restart: unless-stopped
    networks:
      - tkj-network

networks:
  tkj-network:
    driver: bridge
